version: 1
formatters:
  simple:
    format: '[%(asctime)s][%(threadName)s][%(levelname)-5s][%(name)s.%(funcName)s] - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    when: D
    interval: 1
    level: DEBUG
    formatter: simple
    filename: 'app-log.log'
    encoding: utf8
# external lib
loggers:
  injector:
    level: DEBUG
root:
  level: DEBUG
  handlers:
    - console
    - file
disable_existing_loggers: false   